### ISSUE TITLE
Please make the gradio demo fast for those without gpu

### ISSUE THREAD

**Issue by opajiqw** [LPengYang/MotionClone#10]

**Comment by LPengYang** [comment]
Sorry for being late. We have updated the code. Now MotionClone is able to 1) directly performs motion customization without cumbersome video inversion ; 2) significantly reduces memory consumption.
In our experiments, For 16×512×512 text-to-video, the memory consumption is about 14GB . For MotionClone combined with image-to-video or sketch-to-video, the memory is about 22 GB. The inference speed is also significantly faster than previous verison. Hope this helps.
