### ISSUE TITLE
Paper Error

### ISSUE THREAD

**Issue by wenhuchen** [LPengYang/MotionClone#12]
<img width="1232" alt="Screenshot 2024-07-14 at 11 54 45 PM" src="https://github.com/user-attachments/assets/45cf427c-b699-468c-8ff6-e5eb70526de2">
I'm pretty sure your formula is wrong here. This should be the derivative of $\frac{\partial g_m}{\partial z_t}$ instead of g_m itself. Your code implementation also shows that is the correct one.

**Comment by Bujiazi** [comment]
Thank you for your attention to MotionClone 🌹. We sincerely apologize for the ambiguity and confusion caused 😂. Your point is correct, and we will correct the formula in our paper soon.

**Comment by Yukun66** [comment]
> <img alt="Screenshot 2024-07-14 at 11 54 45 PM" width="1232" src="https://private-user-images.githubusercontent.com/1457702/348595649-45cf427c-b699-468c-8ff6-e5eb70526de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDIwMjAsIm5iZiI6MTcyMzMwMTcyMCwicGF0aCI6Ii8xNDU3NzAyLzM0ODU5NTY0OS00NWNmNDI3Yy1iNjk5LTQ2OGMtOGZmNi1lNWViNzA1MjZkZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQ1NTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFiYTk0OGY5OWNmMmRjNWVkODIwOTI0N2Q3OWM1YzI5ZjIzMWM2NzAwNDY1MTk1MTVjMGMzMGVmNjIwYmNlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DF58QK4RerhJ1vCXT01V1dxSHg4nxtksM_1lwLO0gZo"> I'm pretty sure your formula is wrong here. This should be the derivative of $\frac{\partial g_m}{\partial z_t}$ instead of g_m itself. Your code implementation also shows that is the correct one.

Hi, could you please explain why the formula (9) should be $\frac{\partial g_m}{\partial z_t}$ instead of g_m ? Why the appearance component in (10) is NOT in this form? Thx!

**Comment by LeonXu127** [comment]
![image](https://github.com/user-attachments/assets/c3c6dc7b-2790-4d34-94ec-78dc341bc929)
Could you please explain why the additional energy function term makes sense here? I did not find clues of this term in the original CFG paper. I would be appreciated if you can provide any document to learn or explain about this energy function term.

**Comment by luo0207** [comment]
@Bujiazi  I also have the same question with @LeonXu127 .  Could you please explain this energy function term?

**Comment by luo0207** [comment]
@LeonXu127  I understand it. The energy term is wrong in the paper but correct in the code, actually MotionClone follows the paper [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/pdf/2105.05233), which uses labels to guide the diffusion procedures, e.g., MotionClone uses the semantic and motion information from example video to guide the diffusion process.  The corresponding code is [code](https://github.com/Bujiazi/MotionClone/blob/33132fb051cbb3833ff6a72eba817ea7746fa816/motionclone/pipelines/additional_components.py#L100)

**Comment by LeonXu127** [comment]
> @LeonXu127 I understand it. As said by @wenhuchen , the energy term is wrong in the paper but correct in the code, actually MotionClone follows the paper [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/pdf/2105.05233), which uses labels to guide the diffusion procedures, e.g., MotionClone uses the semantic and motion information from example video to guide the diffusion process. The corresponding code is [code](https://github.com/Bujiazi/MotionClone/blob/33132fb051cbb3833ff6a72eba817ea7746fa816/motionclone/pipelines/additional_components.py#L100)

Thanks a lot! I will look through the classifier guidance paper and code.

**Comment by LPengYang** [comment]
> > @LeonXu127 I understand it. As said by @wenhuchen , the energy term is wrong in the paper but correct in the code, actually MotionClone follows the paper [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/pdf/2105.05233), which uses labels to guide the diffusion procedures, e.g., MotionClone uses the semantic and motion information from example video to guide the diffusion process. The corresponding code is [code](https://github.com/Bujiazi/MotionClone/blob/33132fb051cbb3833ff6a72eba817ea7746fa816/motionclone/pipelines/additional_components.py#L100)
> 
> Thanks a lot! I will look through the classifier guidance paper and code.

Sorry for being late. We have released the latest paper and corresponding code. Now MotionClone is able to perform motion customization without cumbersome inversion processes and significantly reduce memory consumption (~14GB for 16×512×512 text-to-video generation). Hope this helps.

**Comment by tyrink** [comment]
> > > @LeonXu127 I understand it. As said by @wenhuchen , the energy term is wrong in the paper but correct in the code, actually MotionClone follows the paper [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/pdf/2105.05233), which uses labels to guide the diffusion procedures, e.g., MotionClone uses the semantic and motion information from example video to guide the diffusion process. The corresponding code is [code](https://github.com/Bujiazi/MotionClone/blob/33132fb051cbb3833ff6a72eba817ea7746fa816/motionclone/pipelines/additional_components.py#L100)
> > 
> > 
> > Thanks a lot! I will look through the classifier guidance paper and code.
> 
> Sorry for being late. We have released the latest paper and corresponding code. Now MotionClone is able to perform motion customization without cumbersome inversion processes and significantly reduce memory consumption (~14GB for 16×512×512 text-to-video generation). Hope this helps.

hi, could you explain why the ddim inversion process can be replaced by the addition of random noise to provide temporal guidance?

**Comment by LPengYang** [comment]
Hello~, Thanks for your attention to our work.  In our experiments, it is observed that the motion guidance provided by DDIM inversion and direct noise-adding exhibits similar guidance strength.  We speculate that this is because DDIM inversion does not yield perfect noisy latents (the inversion trajectory of DDIM inversion does not match the real sampling trajectory, as revealed in “Null-text Inversion"), thereby reducing the quality gap between it and direct noise-adding. Additionally, the direct addition of noise for distribution shifting aligns with the operations performed during the training phase.
