### ISSUE TITLE
camera pose config,such as “apple-->iphone"

### ISSUE THREAD

**Issue by balabala932131** [LPengYang/MotionClone#14]
Nice work!

Can you provide some configurations for camera poses? I'd like to try some examples.

Looking forward to your reply!

**Comment by LPengYang** [comment]
Sorry for being late. We have updated the code. Now you can perform camera motion cutomization via " python t2v_video_sample.py --inference_config "configs/t2v_camera.yaml" --examples "configs/t2v_camera.jsonl" ".  In our experiments, MotionClone showcases impressive proficiency in camera motion scenarios. Moreover, MotionClone also supports image-to-video and sketch-to-video. More details are available in the README file. Hope this helps.
