### ISSUE TITLE
does this work for image to video generation?

### ISSUE THREAD

**Issue by SkylerZheng** [LPengYang/MotionClone#9]
Wondering if this can be generalized to I2V. Like copy/clone the referenced video motion to the image to video generation

**Comment by Bujiazi** [comment]
Hello, thanks for your attention to MotionClone 🌹. If MotionClone selects a base model similar to AnimateDiff that supports image-to-video (I2V) frameworks, achieving I2V motion cloning will be possible 😄. We are currently conducting relevant experiments and may release I2V version in future updates.

**Comment by liupengcnu** [comment]
> nice work! when you will release the  I2V version?

**Comment by LPengYang** [comment]
Sorry for being late.  We have updated the code. Now MotionClone supports image-to-video and sketch-to-video. More details are available on README file.
